const product = [
    // --- Breakfast (1-10) ---
    {id: 'p1', name: 'Fluffy Pancakes', image: 'https://kitchenfunwithmy3sons.com/wp-content/uploads/2022/06/fluffy-pancakes-feature.jpg', info: 'Classic vanilla pancakes', price: '20'},
    {id: 'p2', name: 'Belgian Waffles', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Crispy waffles with syrup', price: '25'},
    {id: 'p3', name: 'French Toast', image: 'https://kitchenfunwithmy3sons.com/wp-content/uploads/2022/06/fluffy-pancakes-feature.jpg', info: 'Golden brown toast', price: '22'},
    {id: 'p4', name: 'Masala Omelette', image: 'https://www.homemadeinterest.com/wp-content/uploads/2017/02/Ice-Cream-Waffle-Sundae_featured.jpg', info: 'Spicy egg omelette', price: '15'},
    {id: 'p5', name: 'Hash Browns', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Crispy potato patties', price: '18'},
    {id: 'p6', name: 'Bagel & Cream Cheese', image: 'https://www.mybakingaddiction.com/wp-content/uploads/2022/08/plated-blueberry-cheesecake-hero.jpg', info: 'Toasted bagel', price: '30'},
    {id: 'p7', name: 'Fruit Salad', image: 'https://www.homemadeinterest.com/wp-content/uploads/2017/02/Ice-Cream-Waffle-Sundae_featured.jpg', info: 'Fresh seasonal fruits', price: '25'},
    {id: 'p8', name: 'Oatmeal Bowl', image: 'https://images.immediate.co.uk/production/volatile/sites/30/2020/08/recipe-image-legacy-id-1163514_11-86c1f82.jpg?quality=90&resize=440,400', info: 'Healthy oats with honey', price: '20'},
    {id: 'p9', name: 'Breakfast Burrito', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Eggs and beans wrap', price: '35'},
    {id: 'p10', name: 'Croissant', image: 'https://www.mybakingaddiction.com/wp-content/uploads/2022/08/plated-blueberry-cheesecake-hero.jpg', info: 'Buttery flaky pastry', price: '28'},

    // --- Burgers & Sandwiches (11-20) ---
    {id: 'p11', name: 'Classic Veg Burger', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Potato patty burger', price: '40'},
    {id: 'p12', name: 'Cheese Burger', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Loaded with cheddar', price: '50'},
    {id: 'p13', name: 'Paneer Burger', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Spicy paneer patty', price: '60'},
    {id: 'p14', name: 'Aloo Tikki Burger', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Indian street style', price: '35'},
    {id: 'p15', name: 'Club Sandwich', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Triple layer sandwich', price: '55'},
    {id: 'p16', name: 'Grilled Cheese', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Melty mozzarella toast', price: '30'},
    {id: 'p17', name: 'Bombay Sandwich', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Spicy chutney sandwich', price: '25'},
    {id: 'p18', name: 'Corn & Spinach Sandwich', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Healthy and creamy', price: '45'},
    {id: 'p19', name: 'Mushroom Burger', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Grilled mushroom patty', price: '65'},
    {id: 'p20', name: 'Subway Melt', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Long bun sub', price: '70'},

    // --- Pizza & Pasta (21-30) ---
    {id: 'p21', name: 'Margherita Pizza', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Classic cheese pizza', price: '99'},
    {id: 'p22', name: 'Farmhouse Pizza', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Loaded veggies', price: '120'},
    {id: 'p23', name: 'Peppy Paneer Pizza', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Spicy paneer cubes', price: '130'},
    {id: 'p24', name: 'Mushroom Pizza', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Cheese and mushrooms', price: '110'},
    {id: 'p25', name: 'Corn Delight Pizza', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Sweet corn special', price: '100'},
    {id: 'p26', name: 'White Sauce Pasta', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Creamy penne', price: '80'},
    {id: 'p27', name: 'Red Sauce Pasta', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Tangy tomato arrabbiata', price: '80'},
    {id: 'p28', name: 'Mac N Cheese', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'American classic', price: '90'},
    {id: 'p29', name: 'Lasagna', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Baked layered pasta', price: '150'},
    {id: 'p30', name: 'Garlic Bread', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Side dish special', price: '40'},

    // --- Indian Main Course (31-40) ---
    {id: 'p31', name: 'Paneer Butter Masala', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Rich creamy curry', price: '140'},
    {id: 'p32', name: 'Dal Makhani', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Slow cooked lentils', price: '120'},
    {id: 'p33', name: 'Chana Masala', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Spicy chickpeas', price: '110'},
    {id: 'p34', name: 'Aloo Gobi', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Potato cauliflower dry', price: '90'},
    {id: 'p35', name: 'Palak Paneer', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Spinach cottage cheese', price: '130'},
    {id: 'p36', name: 'Butter Naan', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Tandoori bread', price: '30'},
    {id: 'p37', name: 'Garlic Naan', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Garlic flavor bread', price: '35'},
    {id: 'p38', name: 'Jeera Rice', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Cumin rice', price: '60'},
    {id: 'p39', name: 'Veg Biryani', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Aromatic rice dish', price: '120'},
    {id: 'p40', name: 'Raita', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Yogurt side dish', price: '40'},

    // --- Chinese (41-50) ---
    {id: 'p41', name: 'Veg Noodles', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Hakka noodles', price: '80'},
    {id: 'p42', name: 'Schezwan Noodles', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Spicy red noodles', price: '90'},
    {id: 'p43', name: 'Fried Rice', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Wok tossed rice', price: '85'},
    {id: 'p44', name: 'Manchurian Dry', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Veggie balls starter', price: '95'},
    {id: 'p45', name: 'Manchurian Gravy', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Main course gravy', price: '100'},
    {id: 'p46', name: 'Chilli Paneer', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Spicy cottage cheese', price: '120'},
    {id: 'p47', name: 'Spring Rolls', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Crispy rolls', price: '60'},
    {id: 'p48', name: 'Honey Chilli Potato', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Sweet and spicy', price: '70'},
    {id: 'p49', name: 'Manchow Soup', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Spicy soup with noodles', price: '50'},
    {id: 'p50', name: 'Hot & Sour Soup', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Tangy soup', price: '50'},

    // --- Snacks (51-60) ---
    {id: 'p51', name: 'French Fries', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Salted potato fries', price: '50'},
    {id: 'p52', name: 'Peri Peri Fries', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Spicy fries', price: '60'},
    {id: 'p53', name: 'Cheesy Fries', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Loaded with cheese', price: '70'},
    {id: 'p54', name: 'Nachos with Salsa', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Corn chips dip', price: '80'},
    {id: 'p55', name: 'Cheese Balls', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Fried cheese snacks', price: '65'},
    {id: 'p56', name: 'Garlic Pops', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Bite sized bread', price: '40'},
    {id: 'p57', name: 'Tacos', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Mexican shells', price: '55'},
    {id: 'p58', name: 'Onion Rings', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Fried onion circles', price: '45'},
    {id: 'p59', name: 'Veg Puff', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Bakery snack', price: '20'},
    {id: 'p60', name: 'Samosa', image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJBsQzYfonMgV354TmlJmkBA8KSxSHgui_WA&s', info: 'Indian potato pastry', price: '15'},

    // --- Cakes & Desserts (61-70) ---
    {id: 'p61', name: 'Choco Lava Cake', image: 'https://images.getrecipekit.com/20250325120225-how-20to-20make-20chocolate-20molten-20lava-20cake-20in-20the-20microwave.png?width=650&quality=90&', info: 'Molten chocolate center', price: '60'},
    {id: 'p62', name: 'Blueberry Cheesecake', image: 'https://www.mybakingaddiction.com/wp-content/uploads/2022/08/plated-blueberry-cheesecake-hero.jpg', info: 'Creamy cheese cake', price: '90'},
    {id: 'p63', name: 'Red Velvet Cake', image: 'https://www.mybakingaddiction.com/wp-content/uploads/2022/08/plated-blueberry-cheesecake-hero.jpg', info: 'Red sponge cake', price: '80'},
    {id: 'p64', name: 'Chocolate Truffle', image: 'https://images.getrecipekit.com/20250325120225-how-20to-20make-20chocolate-20molten-20lava-20cake-20in-20the-20microwave.png?width=650&quality=90&', info: 'Dark chocolate', price: '75'},
    {id: 'p65', name: 'Black Forest', image: 'https://images.getrecipekit.com/20250325120225-how-20to-20make-20chocolate-20molten-20lava-20cake-20in-20the-20microwave.png?width=650&quality=90&', info: 'Cherry and cream', price: '70'},
    {id: 'p66', name: 'Brownie', image: 'https://images.getrecipekit.com/20250325120225-how-20to-20make-20chocolate-20molten-20lava-20cake-20in-20the-20microwave.png?width=650&quality=90&', info: 'Fudgy square', price: '50'},
    {id: 'p67', name: 'Brownie with IceCream', image: 'https://www.homemadeinterest.com/wp-content/uploads/2017/02/Ice-Cream-Waffle-Sundae_featured.jpg', info: 'Sizzling hot and cold', price: '80'},
    {id: 'p68', name: 'Cupcake', image: 'https://www.mybakingaddiction.com/wp-content/uploads/2022/08/plated-blueberry-cheesecake-hero.jpg', info: 'Small frosted cake', price: '30'},
    {id: 'p69', name: 'Donut', image: 'https://www.theflourhandprint.com/wp-content/uploads/2019/11/chocolate-syrup-recipe-12-500x500.jpg', info: 'Glazed ring', price: '40'},
    {id: 'p70', name: 'Mousse', image: 'https://images.getrecipekit.com/20250325120225-how-20to-20make-20chocolate-20molten-20lava-20cake-20in-20the-20microwave.png?width=650&quality=90&', info: 'Airy chocolate dessert', price: '45'},

    // --- Ice Creams & Shakes (71-80) ---
    {id: 'p71', name: 'Vanilla Scoop', image: 'https://www.homemadeinterest.com/wp-content/uploads/2017/02/Ice-Cream-Waffle-Sundae_featured.jpg', info: 'Simple vanilla', price: '30'},
    {id: 'p72', name: 'Chocolate Scoop', image: 'https://www.homemadeinterest.com/wp-content/uploads/2017/02/Ice-Cream-Waffle-Sundae_featured.jpg', info: 'Rich chocolate', price: '35'},
    {id: 'p73', name: 'Strawberry Scoop', image: 'https://www.homemadeinterest.com/wp-content/uploads/2017/02/Ice-Cream-Waffle-Sundae_featured.jpg', info: 'Fruit berry', price: '35'},
    {id: 'p74', name: 'Butterscotch Scoop', image: 'https://www.homemadeinterest.com/wp-content/uploads/2017/02/Ice-Cream-Waffle-Sundae_featured.jpg', info: 'Crunchy sweet', price: '40'},
    {id: 'p75', name: 'Ice Cream Sundae', image: 'https://www.homemadeinterest.com/wp-content/uploads/2017/02/Ice-Cream-Waffle-Sundae_featured.jpg', info: 'Mix scoops with nuts', price: '80'},
    {id: 'p76', name: 'Chocolate Milkshake', image: 'https://www.theflourhandprint.com/wp-content/uploads/2019/11/chocolate-syrup-recipe-12-500x500.jpg', info: 'Thick shake', price: '60'},
    {id: 'p77', name: 'Oreo Shake', image: 'https://www.theflourhandprint.com/wp-content/uploads/2019/11/chocolate-syrup-recipe-12-500x500.jpg', info: 'Cookie crumble shake', price: '70'},
    {id: 'p78', name: 'Kitkat Shake', image: 'https://www.theflourhandprint.com/wp-content/uploads/2019/11/chocolate-syrup-recipe-12-500x500.jpg', info: 'Wafer chocolate shake', price: '75'},
    {id: 'p79', name: 'Mango Shake', image: 'https://www.homemadeinterest.com/wp-content/uploads/2017/02/Ice-Cream-Waffle-Sundae_featured.jpg', info: 'Seasonal fruit shake', price: '60'},
    {id: 'p80', name: 'Cold Coffee', image: 'https://www.theflourhandprint.com/wp-content/uploads/2019/11/chocolate-syrup-recipe-12-500x500.jpg', info: 'Iced coffee blend', price: '50'},

    // --- Hot Beverages (81-90) ---
    {id: 'p81', name: 'Masala Chai', image: 'https://www.allrecipes.com/thmb/lnb_004MI6wGuJXQ-uDxMUNZmQk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20211-creamy-hot-cocoa-DDMFS-4x3-ed6183b2bbb74bbba4a06a78e4d72350.jpg', info: 'Spiced Indian tea', price: '20'},
    {id: 'p82', name: 'Ginger Tea', image: 'https://www.allrecipes.com/thmb/lnb_004MI6wGuJXQ-uDxMUNZmQk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20211-creamy-hot-cocoa-DDMFS-4x3-ed6183b2bbb74bbba4a06a78e4d72350.jpg', info: 'Tea with ginger root', price: '20'},
    {id: 'p83', name: 'Hot Chocolate', image: 'https://www.allrecipes.com/thmb/lnb_004MI6wGuJXQ-uDxMUNZmQk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20211-creamy-hot-cocoa-DDMFS-4x3-ed6183b2bbb74bbba4a06a78e4d72350.jpg', info: 'Warm cocoa drink', price: '45'},
    {id: 'p84', name: 'Cappuccino', image: 'https://www.allrecipes.com/thmb/lnb_004MI6wGuJXQ-uDxMUNZmQk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20211-creamy-hot-cocoa-DDMFS-4x3-ed6183b2bbb74bbba4a06a78e4d72350.jpg', info: 'Foamy coffee', price: '50'},
    {id: 'p85', name: 'Espresso', image: 'https://www.allrecipes.com/thmb/lnb_004MI6wGuJXQ-uDxMUNZmQk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20211-creamy-hot-cocoa-DDMFS-4x3-ed6183b2bbb74bbba4a06a78e4d72350.jpg', info: 'Strong black coffee', price: '40'},
    {id: 'p86', name: 'Latte', image: 'https://www.allrecipes.com/thmb/lnb_004MI6wGuJXQ-uDxMUNZmQk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20211-creamy-hot-cocoa-DDMFS-4x3-ed6183b2bbb74bbba4a06a78e4d72350.jpg', info: 'Milky coffee', price: '55'},
    {id: 'p87', name: 'Mocha', image: 'https://www.allrecipes.com/thmb/lnb_004MI6wGuJXQ-uDxMUNZmQk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20211-creamy-hot-cocoa-DDMFS-4x3-ed6183b2bbb74bbba4a06a78e4d72350.jpg', info: 'Chocolate coffee', price: '60'},
    {id: 'p88', name: 'Green Tea', image: 'https://www.allrecipes.com/thmb/lnb_004MI6wGuJXQ-uDxMUNZmQk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20211-creamy-hot-cocoa-DDMFS-4x3-ed6183b2bbb74bbba4a06a78e4d72350.jpg', info: 'Healthy herbal tea', price: '30'},
    {id: 'p89', name: 'Lemon Tea', image: 'https://www.allrecipes.com/thmb/lnb_004MI6wGuJXQ-uDxMUNZmQk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20211-creamy-hot-cocoa-DDMFS-4x3-ed6183b2bbb74bbba4a06a78e4d72350.jpg', info: 'Citrus infused tea', price: '25'},
    {id: 'p90', name: 'Tomato Soup', image: 'https://www.allrecipes.com/thmb/lnb_004MI6wGuJXQ-uDxMUNZmQk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20211-creamy-hot-cocoa-DDMFS-4x3-ed6183b2bbb74bbba4a06a78e4d72350.jpg', info: 'Warm starter', price: '40'},

    // --- Cold Drinks (91-100) ---
    {id: 'p91', name: 'Coke', image: 'https://www.theflourhandprint.com/wp-content/uploads/2019/11/chocolate-syrup-recipe-12-500x500.jpg', info: 'Chilled cola', price: '20'},
    {id: 'p92', name: 'Pepsi', image: 'https://www.theflourhandprint.com/wp-content/uploads/2019/11/chocolate-syrup-recipe-12-500x500.jpg', info: 'Chilled soda', price: '20'},
    {id: 'p93', name: 'Sprite', image: 'https://www.theflourhandprint.com/wp-content/uploads/2019/11/chocolate-syrup-recipe-12-500x500.jpg', info: 'Lemon lime soda', price: '20'},
    {id: 'p94', name: 'Fanta', image: 'https://www.theflourhandprint.com/wp-content/uploads/2019/11/chocolate-syrup-recipe-12-500x500.jpg', info: 'Orange soda', price: '20'},
    {id: 'p95', name: 'Iced Tea', image: 'https://www.allrecipes.com/thmb/lnb_004MI6wGuJXQ-uDxMUNZmQk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20211-creamy-hot-cocoa-DDMFS-4x3-ed6183b2bbb74bbba4a06a78e4d72350.jpg', info: 'Lemon chilled tea', price: '40'},
    {id: 'p96', name: 'Lemonade', image: 'https://www.allrecipes.com/thmb/lnb_004MI6wGuJXQ-uDxMUNZmQk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20211-creamy-hot-cocoa-DDMFS-4x3-ed6183b2bbb74bbba4a06a78e4d72350.jpg', info: 'Fresh lime water', price: '25'},
    {id: 'p97', name: 'Orange Juice', image: 'https://www.homemadeinterest.com/wp-content/uploads/2017/02/Ice-Cream-Waffle-Sundae_featured.jpg', info: 'Freshly squeezed', price: '50'},
    {id: 'p98', name: 'Water Bottle', image: 'https://www.homemadeinterest.com/wp-content/uploads/2017/02/Ice-Cream-Waffle-Sundae_featured.jpg', info: 'Mineral water', price: '10'},
    {id: 'p99', name: 'Red Bull', image: 'https://www.theflourhandprint.com/wp-content/uploads/2019/11/chocolate-syrup-recipe-12-500x500.jpg', info: 'Energy drink', price: '100'},
    {id: 'p100', name: 'Buttermilk', image: 'https://www.allrecipes.com/thmb/lnb_004MI6wGuJXQ-uDxMUNZmQk=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20211-creamy-hot-cocoa-DDMFS-4x3-ed6183b2bbb74bbba4a06a78e4d72350.jpg', info: 'Spiced chaas', price: '15'},
];